export const CASPLA_ID_AVAILABLE = 'Caspla IDが利用可能です'
export const CASPLA_ID_NOT_AVAILABLE = 'Caspla IDは既に使用されています。'
export const CONTACT_SYS_ADMIN = 'システム管理者に連絡してください。'
export const REGISTERED_SUCCESSFULLY = '正常に登録されました。'
export const SAVED_CHANGES = '変更を保存しました。'
export const SOMETHING_WENT_WRONG = 'エラーが発生しました。'